# Generated by Django 5.0.1 on 2024-01-24 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('abbr', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('state_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state_select.statetable')),
            ],
        ),
        migrations.CreateModel(
            name='Towns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('counties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state_select.counties')),
            ],
        ),
    ]
